--- #YAML:1.0
name:                Authen-Simple-WebForm
version:             0.01
abstract:            Simple authentication against existing web based forms.
license:             ~
author:              
    - Joshua I. Miller <unrtst@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Authen::Simple::Adapter:       0
    HTTP::Cookies:                 0
    LWP:                           0
    LWP::ConnCache:                0
    Test::More:                    0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
